// 启动状态
export const WILL_ENTER_APP = 'WILL_ENTER_APP'
export const USER_LOGINED = 'USER_LOGINED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const AFTER_LOGIN = 'AFTER_LOGIN'
export const ENTER_SLIDE = 'ENTER_SLIDE'
export const APP_BOOTED = 'APP_BOOTED'

// 全局组件
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// 视频 列表
export const FETCH_CREATIONS_START = 'FETCH_CREATIONS_START'
export const FETCH_CREATIONS_REJECTED = 'FETCH_CREATIONS_REJECTED'
export const FETCH_CREATIONS_FULFILLED = 'FETCH_CREATIONS_FULFILLED'

// 视频 详情页
export const PAUSED = 'PAUSED'
export const PLAY = 'PLAY'

// 评论 列表
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START'
export const FETCH_COMMENTS_REJECTED = 'FETCH_COMMENTS_REJECTED'
export const FETCH_COMMENTS_FULFILLED = 'FETCH_COMMENTS_FULFILLED'

// 新增 列表
export const CREATIONS_READY = 'CREATIONS_READY'

// 评论 表单
export const WILL_COMMENT = 'WILL_COMMENT'
export const SEND_COMMENTS_START = 'SEND_COMMENTS_START'
export const SEND_COMMENTS_REJECTED = 'SEND_COMMENTS_REJECTED'
export const SEND_COMMENTS_FULFILLED = 'SEND_COMMENTS_FULFILLED'

// 评论 浮窗
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

// 账户更新
export const USER_UPDATED = 'USER_UPDATED'

